server:
  port: 8088

spring:
  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/wty?serverTimezone=GMT&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    url: jdbc:mysql://127.0.0.1:3306/college_sys?serverTimezone=GMT&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://127.0.0.1:3306/travel_reimbursement_system?serverTimezone=GMT&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
  # 限制文件上传的最大大小
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1

mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.jxd.mptest.model
